# Generated by Django 3.2.16 on 2023-01-23 01:12

import django.core.validators

from django.db import migrations, models

import core.utils.groups_validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group_name",
                    models.CharField(
                        max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(2)]
                    ),
                ),
                (
                    "amount_students",
                    models.PositiveIntegerField(
                        default=30, null=True, validators=[core.utils.groups_validators.amount_students_validator]
                    ),
                ),
                ("head_teacher", models.CharField(max_length=120, null=True)),
                ("faculty", models.CharField(max_length=120, null=True)),
                ("head_teacher_email", models.EmailField(max_length=120, null=True)),
                ("head_teacher_phone", models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
