# Generated by Django 3.2.16 on 2023-02-19 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Groups", "verbose_name_plural": "All groups"},
        ),
    ]
