# Generated by Django 3.2.16 on 2023-02-19 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_teacher_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "All teachers"},
        ),
    ]
