# Generated by Django 3.2.16 on 2023-01-23 01:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.utils.student_validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_name",
                    models.CharField(
                        max_length=120,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            core.utils.student_validators.first_name_validator,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(2)]
                    ),
                ),
                ("email", models.EmailField(max_length=120, null=True)),
                (
                    "grade",
                    models.PositiveIntegerField(
                        default=0, null=True, validators=[core.utils.student_validators.grade_validator]
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
                ("department", models.CharField(max_length=300, null=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="groups.group")),
            ],
        ),
    ]
