# Generated by Django 3.2.16 on 2023-01-23 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="id",
        ),
        migrations.AddField(
            model_name="students",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
