# Generated by Django 3.2.16 on 2023-01-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_auto_20230123_0136"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="static/img/"),
        ),
    ]
