# Generated by Django 3.2.16 on 2023-01-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_students_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="summary",
            field=models.FileField(blank=True, max_length=200, upload_to="files/"),
        ),
    ]
