# Generated by Django 3.2.16 on 2023-01-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0004_students_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_students_in_this_group",
                to="groups.group",
            ),
        ),
    ]
