# Generated by Django 3.2.16 on 2023-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(default="static/img/avatar.png/", upload_to="static/img/profiles/"),
        ),
    ]
